language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

branches:
  only:
    - master
    - develop
    
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mkdir -p $HOME/.composer
  - echo -e "{\"config\":{\"github-oauth\":\{\"github.com\":\"NuUCEFAdIrYSbAvdUa3BA6d5ZIdBieDcE0JTNS0iXJG5KKCNhruOouicUXGKwpJVZwGN6pRgnJxlEqKOpTgkMlLis3dMk2txwFqO5O3xKZb+/EfkKuefj5G5Z96zivnEmdKK/fnq0FAOzZaZRmmXVLJPY1ccKcvEu4xpXhjLctE=\"}}}" > $HOME/.composer/config.json
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer install

before_script:
  - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  email: false
