language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

branches:
  only:
    - master
    - develop
    
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer install --prefer-dist

before_script:
  - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  email: false
