language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

branches:
  only:
    - master
    - develop

before_script:
  - mkdir -p build/coverage
  - sh .travis.install.sh

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  email: false
