language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
